# -*- mode: ruby -*-
# vi: set ft=ruby sts=2 ts=2 sw=2 :

# PLUGINS needed:
#   vagrant install plugin \
#       winrm \
#       winrm-fs \
#       winrm-elevated \
#       vagrant-vbguest
#
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "gusztavvargadr/windows-server"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Stop the following boot-up warning:
  # 	Sorry, don't know how to check guest version of Virtualbox Guest Additions on this platform. Stopping installation.
  config.vbguest.auto_update = false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # vb.memory = "1024"
    # vb.cpus = "2"

    # From https://zwischenzugs.com/2017/10/27/ten-things-i-wish-id-known-before-using-vagrant/
    #      https://stackoverflow.com/questions/37562740/enable-dragndrop-in-vagrant-privisioning
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell" do |s|
    s.inline = <<-'SHELL'
     # Do not combine apps in taskbar.
      # From https://www.lifewire.com/how-to-disable-taskbar-button-grouping-2626110
      Set-ItemProperty "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" TaskbarGlomLevel 2

      # Auto-login on boot.
      # See https://support.microsoft.com/en-us/help/324737/how-to-turn-on-automatic-logon-in-windows
      Set-Location "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
      Set-ItemProperty . DefaultUserName vagrant
      Set-ItemProperty . DefaultPassword vagrant
      Set-ItemProperty . AutoAdminLogon 1

      # Install Edge browser (for tests).
      # From https://www.techmesto.com/reinstall-microsoft-edge-windows-10/
      Get-AppXPackage -AllUsers -Name Microsoft.MicrosoftEdge | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml” -verbose}

      # Originally chocolatey-tools installed into "C:\tools"
      $Env:ChocolateyToolsLocation = "C:\Apps"

      # Install chocolatey packages listed in vbguest's shared-folder.
      choco install -y --no-progress --limitoutput C:/vagrant/chocopackages.config

      # TotalCommander: show hidden files.
      Copy-Item  C:/vagrant/wincmd.ini $env:APPDATA/GHISLER/

 
      Restart-Computer -Force
    SHELL
  end
end
