image: Visual Studio 2019
clone_depth: 1
environment:
  MINICONDA: C:\Miniconda37-x64
  MSYS2: C:\msys64
  MY_CONDA_CHANNEL: JRCSTU
  ANACONDA_TOKEN:  # token: all@appveyor
    secure: sdRK/r0uDw/cOg5/gLaVWn+FZwUIyAZYD1xhdzrvNOcZlmetwsoAtgdALiPFurVK
init:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%;%MSYS2%"

install:
  - conda --version

  - |
    conda config --set always_yes yes
    conda config --set anaconda_upload yes
    conda config --prepend channels defaults
    conda config --prepend channels anaconda
    conda config --prepend channels conda-forge
    conda config --prepend channels bioconda
    conda config --prepend channels %MY_CONDA_CHANNEL%

  - conda update -n base conda -y
  - conda install conda-build conda-verify ripgrep anaconda-client constructor
  - conda info -a

  ## DEBUG
  #- conda config --set verbosity 3

build_script:
  ## Build RECIPES
  #
  - conda build --skip-existing --user %MY_CONDA_CHANNEL% --token %ANACONDA_TOKEN% conda\recipes\pandalone\
  - conda build --skip-existing --user %MY_CONDA_CHANNEL% --token %ANACONDA_TOKEN% conda\recipes\wltp\
  - conda build --skip-existing --user %MY_CONDA_CHANNEL% --token %ANACONDA_TOKEN% conda\recipes\syncing\  --no-test
  - conda build --skip-existing --user %MY_CONDA_CHANNEL% --token %ANACONDA_TOKEN% conda\recipes\co2mpas\
  - conda build --skip-existing --user %MY_CONDA_CHANNEL% --token %ANACONDA_TOKEN% conda\recipes\co2mpas_dice\
  - conda build --skip-existing --user %MY_CONDA_CHANNEL% --token %ANACONDA_TOKEN% conda\recipes\flask_session\
  - conda build --skip-existing --user %MY_CONDA_CHANNEL% --token %ANACONDA_TOKEN% conda\recipes\co2wui\
  - conda build --skip-existing --user %MY_CONDA_CHANNEL% --token %ANACONDA_TOKEN% conda\recipes\co2exe\

  ## Build EXE
  #
  - constructor.exe conda/constructs/CO2MPAS/

artifacts:
  - path: "*.exe"
    name: Co2mpasExe
