image: Visual Studio 2019
clone_depth: 1
environment:
  MINICONDA: C:\Miniconda37-x64
  MSYS2: C:\msys64
  MY_CONDA_CHANNEL: JRCSTU
  ANACONDA_TOKEN:  # token: all@appveyor
    secure: sdRK/r0uDw/cOg5/gLaVWn+FZwUIyAZYD1xhdzrvNOcZlmetwsoAtgdALiPFurVK
init:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%;%MSYS2%"

install:
  - conda --version

  - |
    conda config --set always_yes yes
    conda config --set anaconda_upload yes
    conda config --prepend channels defaults
    conda config --prepend channels anaconda
    conda config --prepend channels conda-forge
    conda config --prepend channels bioconda
    conda config --prepend channels %MY_CONDA_CHANNEL%

  - conda update -n base conda -y
  - conda install conda-build conda-verify anaconda-client constructor
  - conda info -a

  ## DEBUG
  #- conda config --set verbosity 3

build_script:
  ## Build RECIPES
  #
  - ps: |
      function conda_build($cwd, $pack) {
        & conda build --skip-existing --user %MY_CONDA_CHANNEL% --token %ANACONDA_TOKEN% "$cwd\conda\recipes\$pack" $args
      }

      workflow build_recipes($cwd) {
        parallel {
          conda_build $cwd  pandalone
          conda_build $cwd  wltp
          conda_build $cwd  syncing  --no-test
          conda_build $cwd  co2mpas
          conda_build $cwd  co2mpas_dice
          conda_build $cwd  flask_session
          conda_build $cwd  co2wui
          conda_build $cwd  co2exe
        }
      }
      $cwd = (Get-Location)
      build_recipes -ErrorAction Stop  $cwd

  ## Build EXE
  #
  - sed -i s/@VER@/%APPVEYOR_BUILD_ID%/  conda/constructs/CO2MPAS/construct.yaml
  - constructor.exe conda/constructs/CO2MPAS/

artifacts:
  - path: "*.exe"
    name: Co2mpasExe
