clone_depth: 1
environment:
  MINICONDA: C:\Miniconda37-x64
  MSYS2: C:\msys64
init:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%;%MSYS2%"

install:
  - conda --version
  - conda update -n base conda -y
  - conda info -a
  - conda install constructor -y

build_script:
  - constructor.exe conda/constructs/CO2MPAS/

artifacts:
  - path: "*.exe"
    name: Co2mpasExe
