{% set name = "validate_email" %}
{% set version = "1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 784719dc5f780be319cdd185dc85dd93afebdb6ebb943811bc4c7c5f9c72aeaf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: http://github.com/syrusakbary/validate_email
  license: LGPL
  license_family: LGPL
  license_file: 
  summary: Validate_email verify if an email address is valid and really exists.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - ankostis
