{% set name = "transitions" %}
{% set version = "0.6.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: afe0f498cf1f3f3b0fc13562011b8895a172df8f891dbb5118923d46e78a96d7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - six
  run:
    - python
    - six

test:
  imports:
    - transitions
    - transitions.extensions
  requires:
    - dill
    - nose
    - pygraphviz

about:
  home: http://github.com/pytransitions/transitions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight, object-oriented Python state machine implementation.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - ankostis
