{% set name = "pandalone" %}
{% set version = "0.2.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a21111cf201201a6bb5a3cb966d25f532db608b362ba1c1ba7cef658f1132bf

build:
  number: 0
  noarch: python
  entry_points:
    - pndl = pandalone.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - setuptools
  host:
    - asteval >=0.9.7
    - future >=0.15.0
    - jsonschema >=2.5, <3
    - numpy
    - pip
    - python >=3.3
    - toolz
  run:
    - asteval >=0.9.7
    - future >=0.15.0
    - jsonschema >=2.5, <3
    - numpy
    - python
    - toolz

test:
  imports:
    - pandalone
    - pandalone.xleash
    - pandalone.xleash.io
  commands:
    - nosetests
  # source_files:
  #   - tests/*
  requires:
    - coverage
    - coveralls
    - ddt
    - nose
    - pandas
    - xlrd

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: European Union Public Licence 1.1 (EUPL 1.1)
  license_family: OTHER
  license_file: ../../../LICENSE.txt
  summary: Process data-trees with relocatable-paths in Python

  doc_url:  https://{{ name }}.readthedocs.org/
  dev_url:  https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - ankostis
