{% set name = "co2mpas" %}
{% set version = "4.0.0.dev0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../../../co2mpas.git
build:
  number: 1
  noarch: python
  entry_points:
    - {{ name }} = {{ name }}.cli:cli

requirements:
  host:
    - python >=3.5
    - menuinst                # [win]
    # model deps
    - lmfit>=0.9.7
    - numpy
    - PyYAML
    - regex
    - schedula>=0.3.2
    - schema
    - scikit-learn
    - scipy
    - tqdm
    - wltp <1.0.0                 # new jsonschema & incompatible IOs in 1+
    - py-xgboost
    ## Extras: io, cli, sync, plot 
    - beautifulsoup4
    - click
    - click-log
    - dill
    - docutils
    - flask
    - graphviz
    - jinja2
    - lxml
    - matplotlib
    - pandalone
    #- pandalone >=0.2.4, <0.3   # new jsonschema in 0.3+
    - pandas >=0.21.0
    - pip
    - Pygments
    - sphinx
    - sphinx-click
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder
    - syncing
    - xlrd
  run:
    - lmfit>=0.9.7
    - numpy
    - PyYAML
    - regex
    - schedula>=0.3.2
    - schema
    - scikit-learn
    - scipy
    - tqdm
    - wltp <1.0.0                 # new jsonschema & incompatible IOs in 1+
    - py-xgboost
    ## Extras: io, cli, sync, plot 
    - beautifulsoup4
    - click
    - click-log
    - dill
    - docutils
    - flask
    - graphviz
    - jinja2
    - lxml
    - matplotlib
    - pandalone
    #- pandalone >=0.2.4, <0.3   # new jsonschema in 0.3+
    - pandas >=0.21.0
    - pip
    - Pygments
    - sphinx
    - sphinx-click
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder
    - syncing
    - xlrd

test:
  imports:
    - co2mpas
    - co2mpas.cli
    - co2mpas.cli.sync
    - co2mpas.core
    - co2mpas.core.load
    - co2mpas.core.model
    - co2mpas.core.model.physical
    - co2mpas.core.model.physical.clutch_tc
    - co2mpas.core.model.physical.driver
    - co2mpas.core.model.physical.engine
    - co2mpas.core.model.physical.gear_box
    - co2mpas.core.model.physical.wheels
    - co2mpas.core.model.physical.defaults
    - co2mpas.core.model.physical.electrics
    - co2mpas.core.model.physical.final_drive
    - co2mpas.core.model.physical.vehicle
    - co2mpas.core.model.selector
    - co2mpas.utils
  source_files:
    - tests/
    - setup.py
    - README.rst
  commands:
    - co2mpas --help
    - co2mpas --version
    - pytest tests --ignore tests/test_io.py --ignore tests/test_cli.py -v
  requires:
    - pytest
    - ddt
    - flake8
    - flake8-builtins
    - flake8-mutable

about:
  home: https://co2mpas.io/
  license: European Union Public Licence 1.1 (EUPL 1.1)
  license_family: OTHER
  license_file: LICENSE
  summary: The Type-Approving vehicle simulator predicting NEDC CO2 emissions from WLTP
  doc_url: https://co2mpas.io/
  dev_url: https://github.com/JRCSTU/CO2MPAS-TA

extra:
  recipe-maintainers:
    - ankostis
