{% set name = "co2mpas" %}
{% set version = "4.1.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "39e9bc769b0edba6f9eb902aa7be1850f4ec282e7005fb89f5ba15725115344e"

build:
  number: 1
  noarch: python
  entry_points:
    - {{ name }} = {{ name }}.cli:cli

requirements:
  host:
    - python >=3.6
    - lmfit >=0.9.7
    - numpy
    - pip
    - pyyaml
    - regex
    - schedula >=0.3.2
    - schema
    - scikit-learn
    - scipy
    - statsmodels
    - tqdm
    # new jsonschema & incompatible IOs in 1+
    - wltp <1.0.0
    - py-xgboost >=0.90  # due to reg:squarederror
    ## Extras: io, cli, sync, plot
    - beautifulsoup4
    - click
    - click-log
    - dill
    - docutils
    - flask
    # Fix for conda graphviz; JRCSTU/co2wui#146
    - python-graphviz==0.8.4  # [win]
    - python-graphviz         # [not win]
    - graphviz
    - jinja2
    - lxml
    - menuinst                # [win]
    - networkx==2.3
    - nose
    - matplotlib    
    # new jsonschema in 0.3+
    - pandalone >=0.2.4, <0.3
    - pandas >=0.21.0
    - pip
    - Pygments
    - sphinx
    - sphinx-click
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder
    - syncing
    - xlrd
  run:
    - lmfit >=0.9.7
    - numpy
    - python >=3.6
    - pyyaml
    - regex
    - schedula >=0.3.2
    - schema
    - scikit-learn
    - scipy
    - statsmodels
    - tqdm
    # new jsonschema & incompatible IOs in 1+
    - wltp <1.0.0
    - py-xgboost >=0.90  # due to reg:squarederror
    ## Extras: io, cli, sync, plot
    - beautifulsoup4
    - click
    - click-log
    - dill
    - docutils
    - flask
    # Fix for conda graphviz; JRCSTU/co2wui#146
    - python-graphviz==0.8.4  # [win]
    - python-graphviz         # [not win]
    - graphviz
    - jinja2
    - lxml
    - networkx==2.3    
    - matplotlib
    - menuinst                # [win]
    # new jsonschema in 0.3+
    - pandalone >=0.2.4, <0.3
    - pandas >=0.21.0
    - pip
    - Pygments
    - sphinx
    - sphinx-click
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder
    - syncing
    - xlrd

test:
  imports:
    - co2mpas
    - co2mpas.cli
    - co2mpas.core
    - co2mpas.core.load
    - co2mpas.core.load.validate
    - co2mpas.core.model
    - co2mpas.core.model.physical
    - co2mpas.core.model.physical.clutch_tc
    - co2mpas.core.model.physical.control
    - co2mpas.core.model.physical.cycle
    - co2mpas.core.model.physical.cycle.WLTP
    - co2mpas.core.model.physical.electrics
    - co2mpas.core.model.physical.electrics.batteries
    - co2mpas.core.model.physical.electrics.batteries.service
    - co2mpas.core.model.physical.electrics.motors
    - co2mpas.core.model.physical.electrics.motors.alternator
    - co2mpas.core.model.physical.engine
    - co2mpas.core.model.physical.gear_box
    - co2mpas.core.model.physical.gear_box.at_gear
    - co2mpas.core.model.selector
    - co2mpas.core.model.selector.models
    - co2mpas.core.write
  commands:
    - co2mpas --help
    - co2mpas --version
  requires:
    - ddt
    - nose >=1.0
    - pytest

about:
  home: "https://github.com/JRCTSU/CO2MPAS-TA"
  license: "European Union Public Licence 1.1 (EUPL 1.1)"
  license_family: "OTHER"
  license_file: LICENSE
  summary: "The Type-Approving vehicle simulator predicting NEDC CO2 emissions from WLTP"
  doc_url: https://co2mpas.readthedocs.org/
  dev_url: https://github.com/JRCSTU/CO2MPAS-TA

extra:
  recipe-maintainers:
    - stefanocorsi
    - ankostis
