{% set name = "co2wui" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../../../co2wui.git
  
build:
  number: 0
  noarch: python
  entry_points:
    - {{ name }} = {{ name }}.app:cli

requirements:
  host:
    - python >=3.5
    # conda stuff
    - menuinst          # [win]
    # app dependencies
    - co2mpas
    - co2mpas_dice
    - Flask
    - Flask-Babel
    - requests
    - schedula
    - Werkzeug
    - click
    - ruamel.yaml
    - syncing
  run:
    - python >=3.6
    - co2mpas
    #- co2mpas_dice  # allow non-TA installations
    - Flask
    - Flask-Babel
    - requests
    - schedula
    - Werkzeug
    - click
    - ruamel.yaml
    - syncing

test:
  imports:
    - co2wui.app
  commands:
    #- co2wui --help  # NO, launches web-browser!
    #- pytest         # all fail :-(
  requires:
    - pytest
    - selenium
    - geckodriver
#app:
#  entry: co2wui run
#  icon:
#  summary: The WebApp to launch co2mpas

about:
  home: https://co2mpas.io/
  license: European Union Public Licence 1.1 (EUPL 1.1)
  license_family: OTHER
  license_file: LICENSE.txt
  summary: the WebUI for co2mpas
  doc_url: https://co2mpas.io/
  dev_url: https://github.com/JRCSTU/co2wui

extra:
  recipe-maintainers:
    - ankostis
