{% set name = "co2wui" %}
{% set version = "0.0.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "6f3a9e84697299bb4f2ec2d70baafe5ff6ba4a0a80c11d7525d4fee94a6aac45"

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - {{ name }} = {{ name }}.app:cli

requirements:
  host:
    - click
    - co2mpas
    - co2mpas_dice
    - flask
    - flask-babel
    - flask_session
    - pip
    - python >=3.6
    - requests
    - ruamel.yaml
    - schedula
    - syncing
    - urllib3
    - werkzeug
    # for `conda build` to run faster
    - ripgrep
  run:
    - click
    - co2mpas
    - co2mpas_dice
    - flask
    - flask-babel
    - flask_session
    - python >=3.6
    - requests
    - ruamel.yaml
    - schedula
    - syncing
    - urllib3
    - werkzeug

test:
  imports:
    - co2wui
    - co2wui.app
    - co2wui.i18n
    - co2wui.__main__
  commands:
    - co2wui --help
    - co2wui --version

about:
  home: "https://github.com/JRCSTU/co2wui"
  license: "European Union Public Licence 1.1 (EUPL 1.1)"
  license_family: "OTHER"
  license_file: ../../../LICENSE.txt
  summary: "WebUI for co2mpas"
  doc_url: "https://co2mpas.readthedocs.org/"
  dev_url: "https://github.com/JRCSTU/co2wui"

extra:
  recipe-maintainers:
    - stefanocorsi
    - ankostis
