{% set name = "co2gui" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f79b99ed5977e3b11677260ac1a2e20d942a671745977097b496e56a09cff211
  patches:
    - 0001-tkNoWinColors.patch
    - 0002-noIdlelibTooltip.patch

build:
  number: 0
  noarch: python
  entry_points:
    - co2gui = co2gui.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >=3.5
    - boltons
    - co2sim
    - co2dice
    # [io] & schedula[plot] optional deps
    - boltons
    - contextvars             # for co2mpare, backported for PY<3.7
    - cryptography
    - dill !=0.2.7
    - docopt
    - openpyxl >=2.4.0
    - pandalone >=0.2.0
    - xlrd
    - pip
    - PyYAML >=3.12
    - toolz
    - tqdm
    - xlsxwriter
  run:
    - python >=3.5
    - boltons
    - co2dice
    - co2sim
    - pillow
    # [io] & schedula[plot] optional deps
    - boltons
    - contextvars             # for co2mpare, backported for PY<3.7
    - cryptography
    - dill !=0.2.7
    - docopt
    - openpyxl >=2.4.0
    - pandalone >=0.2.0
    - xlrd
    - pip
    - PyYAML >=3.12
    - toolz
    - tqdm
    - xlsxwriter

test:
  imports:
    - co2gui
  commands:
    - co2gui --help
  requires:
    - ddt
    - flake8
    - flake8-builtins
    - flake8-mutable
    - pytest
    - pytest-runner

about:
  home: https://co2mpas.io/
  license: European Union Public Licence 1.1 (EUPL 1.1)
  license_family: OTHER
  license_file: ../../../LICENSE.txt
  summary: the tk-GUI for co2sim + co2dice subprojects of co2mpas
  doc_url: https://co2mpas.io/
  dev_url: https://github.com/JRCSTU/CO2MPAS-TA

extra:
  recipe-maintainers:
    - ankostis
