{% set name = "co2mpas_dice" %}
{% set version = "4.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "3f8285346686c235c897ec0395692169e9df0437883497815ea5c57fec5e5ee0"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - {{ name }} = {{ name }}.__main__:cli

requirements:
  host:
    - cryptography
    - lmfit
    - numpy
    - python
    - pyyaml
    - schedula
    - scipy
    # for `conda build` to run faster
    - ripgrep
  run:
    - cryptography
    - lmfit
    - numpy
    - pyyaml
    - schedula
    - scipy

test:
  requires:
    - click
    - click-log
    - docutils
    - flask
    - gunicorn
    - jinja2
    - jsonschema
    - mysql-connector-python
    - pandas
    - tabulate
    - werkzeug
  imports:
    - {{ name }}.declaration
    - {{ name }}.err
    - {{ name }}.crypto
    - {{ name }}.tar
    - {{ name }}.verify
  commands:
    ## Broken without the `server` part.
    #- {{ name }} --help
    #- {{ name }} --version

about:
  home: https://co2mpas.readthedocs.org/
  license: European Union Public Licence 1.1 (EUPL 1.1)
  license_family: OTHER
  license_file: ../../../LICENSE.txt
  summary: Client code for packaging co2mpas results
  doc_url: https://co2mpas.readthedocs.org/
  dev_url: "https://github.com/JRCSTU/DICE"

extra:
  recipe-maintainers:
    - stefanocorsi
    - ankostis
