{% set name = "co2mpas_dice" %}
{% set version = "4.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../../../DICE.git/back-end

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - {{ name }} = {{ name }}.__main__:cli

requirements:
  host:
    - python
    - cryptography
    - lmfit
    - numpy
    - pyyaml
    - schedula
    - scipy
  run:
    - cryptography
    - lmfit
    - numpy
    - pyyaml
    - schedula
    - scipy

test:
  requires:
    - click
    - click-log
    - docutils
    - flask
    - gunicorn
    - jinja2
    - jsonschema
    - mysql-connector-python
    - pandas
    - tabulate
    - werkzeug
  imports:
    - {{ name }}.co2mpas
    - {{ name }}.co2mpas.declaration
    - {{ name }}.co2mpas.verify
    - {{ name }}.validate
    - {{ name }}.crypto
    - {{ name }}.err
    - {{ name }}.config
    - {{ name }}.tar
  commands:
    - {{ name }} --help
    - {{ name }} --version

about:
  home: https://co2mpas.io/
  license: European Union Public Licence 1.1 (EUPL 1.1)
  license_family: OTHER
  license_file: ../../../LICENSE.txt
  summary: Client code for packaging co2mpas results
  doc_url: https://co2mpas.io/
  dev_url: https://github.com/JRCSTU/CO2MPAS-TA

extra:
  recipe-maintainers:
    - ankostis
