{% set name = "syncing" %}
{% set version = "1.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "74f3750939943576fead63efdfae1574e7dbb73a2caf329846e8590ffdc832f5"

build:
  number: 3
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - {{ name }} = {{ name }}.cli:cli

requirements:
  host:
    - python
    - click
    - click-log
    - nose  # due to `https://github.com/vinci1it2000/schedula/issues/14
    - numpy
    - openpyxl
    - pandas
    - pyyaml
    - schedula
    - scipy >=0.3.1
    - setuptools
    # Libs below needed by conda-build docs.
    - beautifulsoup4
    - lxml
    - regex
    - python-graphviz
    - sphinx
    - sphinx-click
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder
    - matplotlib
    - xlrd >=1.0.0
  run:
    - click
    - click-log
    - numpy
    - openpyxl
    - pandas
    - pyyaml
    - schedula
    - scipy >=0.3.1
    - xlrd >=1.0.0

test:
  source_files:
    - test/
    # `test_setup.py` not working :-()
    - setup.py
    - README.rst
  imports:
    - syncing
    - syncing.model
    - syncing.rw
  commands:
    - {{ name }} --help
    - {{ name }} --version
    - pytest test --ignore test/test_setup.py
  requires:
    - ddt
    - beautifulsoup4
    - lxml
    - matplotlib
    - python-graphviz
    - nose
    - regex
    - sphinx
    - sphinx-click
    - sphinx_rtd_theme
    - sphinxcontrib-restbuilder

about:
  home: "https://github.com/vinci1it2000/syncing"
  license: "European Union Public Licence 1.1 (EUPL 1.1)"
  license_family: "OTHER"
  license_file: ../../../LICENSE.txt
  summary: "Time series synchronization and resample library."
  doc_url: ""
  dev_url: "https://github.com/vinci1it2000/syncing"

extra:
  recipe-maintainers:
    - stefanocorsi
    - ankostis
